# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ZMeducation2.0' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

pod 'AFNetworking', '~> 3.1.0'
pod 'ReactiveCocoa', '~> 2.4.7'
pod 'SDWebImage', '~> 4.0.0'
pod 'YYModel', '~> 1.0.4'
pod 'MJRefresh', '~> 3.1.12'

end
